// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR4B587X4q2BdggWVVw-AqjJMEVAaZKUw',
    appId: '1:1071455479389:android:123b7a29bd74e9991d0fb4',
    messagingSenderId: '1071455479389',
    projectId: 'letterscirious',
    storageBucket: 'letterscirious.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj0oFpM9D9it_LKgFJlYLc1DEnIpPFNEY',
    appId: '1:1071455479389:ios:e09afeb0a31a118e1d0fb4',
    messagingSenderId: '1071455479389',
    projectId: 'letterscirious',
    storageBucket: 'letterscirious.appspot.com',
    iosBundleId: 'com.example.letters',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj0oFpM9D9it_LKgFJlYLc1DEnIpPFNEY',
    appId: '1:1071455479389:ios:e09afeb0a31a118e1d0fb4',
    messagingSenderId: '1071455479389',
    projectId: 'letterscirious',
    storageBucket: 'letterscirious.appspot.com',
    iosBundleId: 'com.example.letters',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWfSgFjCC6ZM2JD3wXjaILP6ULMjmNJkg',
    appId: '1:1071455479389:web:937a6c29bdef272a1d0fb4',
    messagingSenderId: '1071455479389',
    projectId: 'letterscirious',
    authDomain: 'letterscirious.firebaseapp.com',
    storageBucket: 'letterscirious.appspot.com',
    measurementId: 'G-D8MNLE7JJ5',
  );
}
